# Generated by Django 5.1.1 on 2025-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('assistant', 'Assistant'), ('student', 'Student')], max_length=50, verbose_name='Role'),
        ),
    ]
