# Generated by Django 5.1.1 on 2025-05-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_avatar_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('assistant', 'Assistant'), ('student', 'Student')], max_length=50, verbose_name='Role'),
        ),
    ]
