# Generated by Django 5.1.1 on 2025-03-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Credit'),
        ),
    ]
