# Generated by Django 5.1.1 on 2025-04-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
        ('course', '0002_alter_course_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='account.profile', verbose_name='Student'),
        ),
    ]
