# Generated by Django 5.1.1 on 2025-04-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_course_id_courseregistration_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
