# Generated by Django 5.1.1 on 2025-04-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='manager',
        ),
    ]
