# Generated by Django 5.1.1 on 2025-05-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_gpa_alter_profile_role'),
        ('course', '0007_coursematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='registration_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration End At'),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Start At'),
        ),
        migrations.CreateModel(
            name='CourseAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('permession', models.BooleanField(default=False)),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_courses', to='account.profile', verbose_name='Assistant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='course.course', verbose_name='Course')),
            ],
        ),
    ]
