# Generated by Django 5.1.1 on 2025-05-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_gpa_alter_profile_role'),
        ('course', '0008_remove_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='registration_start_at',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='account.profile', verbose_name='Instructor'),
        ),
    ]
