# Generated by Django 5.1.1 on 2025-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_registration_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Start At'),
        ),
    ]
