# Generated by Django 5.1.1 on 2025-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_registration_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='PDF File'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='slides_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Slides File'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='File'),
        ),
    ]
