# Generated by Django 5.1.1 on 2025-04-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('instructor', 'Instructor'), ('assistant', 'Assistant'), ('student', 'Student')], max_length=50, verbose_name='Role'),
        ),
    ]
