# Generated by Django 5.1.1 on 2025-04-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_courseregistration_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='student_id',
            new_name='student',
        ),
    ]
