# Generated by Django 5.1.1 on 2025-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_rename_sloution_solution_content_assignment_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['solution', 'graded_at'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='comment',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='created_at',
            new_name='graded_at',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='score',
        ),
        migrations.AddField(
            model_name='solution',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
