# Generated by Django 5.1.1 on 2025-05-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_gpa_alter_profile_role'),
        ('assignment', '0005_alter_grade_options_rename_comment_grade_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='slug',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignment.solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='account.profile'),
        ),
    ]
